name: Deploy static website to S3

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Prüfen, ob index.html existiert
        run: test -f index.html

      - name: Prüfen, ob style.css existiert
        run: test -f style.css

      - name: HTML auf Grundstruktur prüfen
        run: grep -qi "<html" index.html

      - name: AWS Credentials konfigurieren
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Dateien nach S3 deployen
        run: aws s3 sync . s3://demo-test-silas --delete --exclude ".git/*" --exclude ".github/*" --exclude "terraform*" --exclude "*.zip"